name: Generate Terminal Profile

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Dependencies
        # Install the gifos library
        run: pip install git+https://github.com/x0rzavi/github-readme-terminal.git 

      - name: Commit and Push changes
        run: |
          # Let's list the files just to debug and see what it was actually named
          ls -la *.gif 
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # git add -A grabs ALL new or modified files automatically
          git add -A
          
          git commit -m "Auto-update terminal profile GIF" || exit 0
          git push
